name: Anchore Container Scan

on: [push]

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./ci/anchore-analysis.dockerfile --tag localbuild/scanimage:latest
    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
      uses: anchore/scan-action@main
      with:
        image: "localbuild/scanimage:latest"
        acs-report-enable: true
        fail-build: false
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}
