# When a label like `^Story Points: ([0-9]+)$` is applied, transfer value to the Project Beta `Story Points` column
name: Points Label to Project Field

on:
  issues:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  filter-issues:
    runs-on: ubuntu-latest
    steps:
    - name: match-story-points-label
      run: |
        if [[ ${{ github.event.label.name }} =~ ^Story\ Points:\ ([0-9]+)$ ]] ; then
          echo :set-output name=point_label_value::${BASH_REMATCH[1]}
          echo :set-output name=point_label_match::true
        fi
    - name: echo-label
      if: steps.match-story-points-label.point_label_match == 'true'
      run: |
        echo ${{ steps.match-story-points-label.point_label_value }}

